export const DataSearch = [
    {
        id:0,
        images:[
            require('../../assets/Images/ImagesPosts/foto1.jpg'),
            require('../../assets/Images/ImagesPosts/foto2.jpg'),
            require('../../assets/Images/ImagesStory/foto1.jpg'),
            require('../../assets/Images/ImagesStory/foto2.jpeg'),
            require('../../assets/Images/ImagesPosts/foto3.jpg'),
            require('../../assets/Images/ImagesStory/foto3.jpg'),
        ]
    },
    {
        id:1,
        images:[
            require('../../assets/Images/ImagesPosts/foto4.jpg'),
            require('../../assets/Images/ImagesPosts/foto5.jpg'),
            require('../../assets/Images/ImagesStory/foto4.jpg'),
            require('../../assets/Images/ImagesStory/foto5.jpg'),
            require('../../assets/Images/ImagesPosts/foto6.jpg'),
        ]
    },
    {
        id:2,
        images:[
            require('../../assets/Images/ImagesPosts/foto7.jpg'),
            require('../../assets/Images/ImagesPosts/foto8.jpg'),
            require('../../assets/Images/ImagesStory/foto7.jpeg'),
            require('../../assets/Images/ImagesStory/foto8.png'),
            require('../../assets/Images/ImagesPosts/foto9.jpg'),
            require('../../assets/Images/ImagesStory/foto9.jpg'),
        ]
    },
]